import { InMemoryDbService } from 'angular-in-memory-web-api';



export class InMemoryDataService1 implements InMemoryDbService {
    createDb() {
        const restaurants = [
            {
              'name': 'Esther\'s German Saloon',
              'id': 'esthers',
              'cuisine': 'german',
              'opens': '11:30:00',
              'closes': '22:30:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa',
              'price': 3,
              'Rating': 3,
              'location': '22 Teutonic Ave.',
              'description': 'German home-cooked meals and fifty-eight different beers on tap. To get more authentic, you\'d need to be wearing lederhosen.'
            },
            {
              'name': 'Robatayaki Hachi',
              'id': 'robatayaki',
              'cuisine': 'japanese',
              'opens': '17:30:00',
              'closes': '23:30:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa,Su',
              'price': 4,
              'Rating': 5,
              'location': '8 Hawthorne Ln.',
              'description': 'Japanese food the way you like it. Fast, fresh, grilled.'
            },
            {
              'name': 'BBQ Tofu Paradise',
              'id': 'tofuparadise',
              'cuisine': 'vegetarian',
              'opens': '16:30:00',
              'closes': '20:00:00',
              'daysOpen': 'Mo,We,Fr,Sa,Su',
              'price': 2,
              'Rating': 1,
              'location': '22A King West',
              'description': 'Vegetarians, we have your BBQ needs covered. Our home-made tofu skewers and secret BBQ sauce will have you licking your fingers.'
            },
            {
              'name': 'Le Bateau Rouge',
              'id': 'bateaurouge',
              'cuisine': 'french',
              'opens': '17:00:00',
              'closes': '23:30:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa,Su',
              'price': 5,
              'Rating': 4,
              'location': '2 South Park Dr.',
              'description': 'Fine French dining in a romantic setting. From soupe à l\'oignon to coq au vin, let our chef delight you with a local take on authentic favorites.'
            },
            {
              'name': 'Khartoum Khartoum',
              'id': 'khartoum',
              'cuisine': 'african',
              'opens': '11:00:00',
              'closes': '14:00:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr',
              'price': 3,
              'Rating': 2,
              'location': '1566 Maple Rd.',
              'description': 'African homestyle cuisine, cooked fresh daily.'
            },
            {
              'name': 'Sally\'s Diner',
              'id': 'sallys',
              'cuisine': 'american',
              'opens': '8:30:00',
              'closes': '20:00:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa,Su',
              'price': 4,
              'Rating': 3,
              'location': '96 College Blvd.',
              'description': 'Food like mom cooked, if you grew up in Iowa and mom ran a diner. Try our blue plate special!'
            },
            {
              'name': 'Saucy Piggy',
              'id': 'saucy',
              'cuisine': 'barbecue',
              'opens': '15:00:00',
              'closes': '22:00:00',
              'daysOpen': 'Tu,We,Th,Fr,Sa,Su',
              'price': 3,
              'Rating': 2,
              'location': '623 Industrial Rd.',
              'description': 'Pork. We know how to cook it. Award-winning BBQ sauce, and meat with all the trimmings.'
            },
            {
              'name': 'Czech Point',
              'id': 'czechpoint',
              'cuisine': 'czech/slovak',
              'opens': '10:30:00',
              'closes': '21:30:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa',
              'price': 1,
              'Rating': 4,
              'location': '5567 Queen-Mary Rd',
              'description': 'Make a point of trying our knedlíky and homemade soups. We have free wifi and the best desserts and coffee.'
            },
            {
              'name': 'Der Speisewagen',
              'id': 'speisewagen',
              'cuisine': 'german',
              'opens': '17:00:00',
              'closes': '22:30:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa,Su',
              'price': 3,
              'Rating': 5,
              'location': '402 College Blvd.',
              'description': 'Award-winning schnitzel and other favorites. Look for our restored food truck in the NE corner of the College St lot.'
            },
            {
              'name': 'Beijing Express',
              'id': 'beijing',
              'cuisine': 'chinese',
              'opens': '11:00:00',
              'closes': '22:30:00',
              'daysOpen': 'Mo,We,Fr,Sa,Su',
              'price': 2,
              'Rating': 4,
              'location': '38 Teutonic Ave.',
              'description': 'Fast, healthy, Chinese food. Family specials for takeout or delivery. Try our Peking Duck!'
            },
            {
              'name': 'Satay Village',
              'id': 'satay',
              'cuisine': 'thai',
              'opens': '17:30:00',
              'closes': '22:00:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa,Su',
              'price': 4,
              'Rating': 2,
              'location': '12 High St.',
              'description': 'Fine dining Thai-style. Wide selection of vegetarian entrées. We also deliver.'
            },
            {
              'name': 'Cancun',
              'id': 'cancun',
              'cuisine': 'mexican',
              'opens': '11:30:00',
              'closes': '23:00:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr',
              'price': 3,
              'Rating': 3,
              'location': '2030 Maple Rd.',
              'description': 'Tacos, tortas, burritos, just the way you like them. Our hot sauce and guacamole are the best in town.'
            },
            {
              'name': 'Curry Up',
              'id': 'curryup',
              'cuisine': 'indian',
              'opens': '17:00:00',
              'closes': '22:00:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa,Su',
              'price': 4,
              'Rating': 5,
              'location': '455 University',
              'description': 'Indian food with a modern twist. We use all-natural ingredients and the finest spices to delight and tempt your palate.'
            },
            {
              'name': 'Carthage',
              'id': 'carthage',
              'cuisine': 'african',
              'opens': '17:00:00',
              'closes': '22:30:00',
              'daysOpen': 'Tu,We,Th,Fr,Sa,Su',
              'price': 2,
              'Rating': 1,
              'location': '59 Court Terrace',
              'description': 'Wholesome food and all the rich flavor of Africa. Try our famous lentil soup.'
            },
            {
              'name': 'Burgerama',
              'id': 'burgerama',
              'cuisine': 'american',
              'opens': '11:00:00',
              'closes': '23:00:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa',
              'price': 5,
              'Rating': 4,
              'location': '456 University',
              'description': 'Grade A beef, freshly ground every day, hand-cut fries, and home-made milkshakes. We make the best burgers in town.'
            },
            {
              'name': 'Three Little Pigs',
              'id': 'littlepigs',
              'cuisine': 'barbecue',
              'opens': '11:30:00',
              'closes': '22:30:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa,Su',
              'price': 3,
              'Rating': 2,
              'location': '12 Summer Court',
              'description': 'Genuine East Texas barbecue. Accept no substitutes!'
            },
            {
              'name': 'Little Prague',
              'id': 'littleprague',
              'cuisine': 'czech/slovak',
              'opens': '11:00:00',
              'closes': '22:00:00',
              'daysOpen': 'Mo,We,Fr,Sa,Su',
              'price': 4,
              'Rating': 3,
              'location': '44 Park Ave',
              'description': 'We\'re famous for our housemade sausage and desserts. Come taste real European cooking.'
            },
            {
              'name': 'Kohl Haus',
              'id': 'kohlhaus',
              'cuisine': 'german',
              'opens': '17:00:00',
              'closes': '22:30:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa,Su',
              'price': 3,
              'Rating': 2,
              'location': '3421 Queen-Mary Rd',
              'description': 'East German specialties, in a family-friendly setting. Come warm up with our delicious soups.'
            },
            {
              'name': 'Dragon\'s Tail',
              'id': 'dragon',
              'cuisine': 'chinese',
              'opens': '17:00:00',
              'closes': '2:00:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr',
              'price': 1,
              'Rating': 4,
              'location': '8 Jasmine Rd.',
              'description': 'Take-out or dine-in Chinese food. Open late. Delivery available'
            },
            {
              'name': 'Hit Me Baby One More Thai',
              'id': 'babythai',
              'cuisine': 'thai',
              'opens': '15:00:00',
              'closes': '22:00:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa,Su',
              'price': 3,
              'Rating': 5,
              'location': '12 Jasmine Rd.',
              'description': 'Thai food with a youthful bar scene. Try our tropical inspired cocktails, or tuck into a plate of our famous pad thai.'
            },
            {
              'name': 'The Whole Tamale',
              'id': 'wholetamale',
              'cuisine': 'mexican',
              'opens': '10:30:00',
              'closes': '21:30:00',
              'daysOpen': 'Tu,We,Th,Fr,Sa,Su',
              'price': 2,
              'Rating': 4,
              'location': '401 University',
              'description': 'The tamale and hot sauce experts. Tamale special changes daily.'
            },
            {
              'name': 'Birmingham Bhangra',
              'id': 'bhangra',
              'cuisine': 'indian',
              'opens': '17:00:00',
              'closes': '22:30:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa',
              'price': 4,
              'Rating': 2,
              'location': '992 Riddick St.',
              'description': 'Curry with a metropolitan twist. Daily specials. Dine-in or takeaway, you choose.'
            },
            {
              'name': 'Taqueria',
              'id': 'taqueria',
              'cuisine': 'mexican',
              'opens': '11:00:00',
              'closes': '22:30:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa,Su',
              'price': 3,
              'Rating': 3,
              'location': '12 North Circle Dr.',
              'description': 'Taqueria y panaderia. Birria served on weekends.'
            },
            {
              'name': 'Pedro\'s',
              'id': 'pedros',
              'cuisine': 'mexican',
              'opens': '17:30:00',
              'closes': '22:00:00',
              'daysOpen': 'Mo,We,Fr,Sa,Su',
              'price': 4,
              'Rating': 5,
              'location': '5521 Alameda',
              'description': 'Pedro\'s has been an Alameda staple for thirty years. Our list of fine tequilas and slow-cooked carnitas will make you a regular.'
            },
            {
              'name': 'Super Wonton Express',
              'id': 'superwonton',
              'cuisine': 'chinese',
              'opens': '11:30:00',
              'closes': '23:00:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa,Su',
              'price': 2,
              'Rating': 1,
              'location': '223 Milliways Ave',
              'description': 'Soups, stir-fries, and more. We cook fast.'
            },
            {
              'name': 'Naan Sequitur',
              'id': 'naansequitur',
              'cuisine': 'indian',
              'opens': '17:00:00',
              'closes': '22:00:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr',
              'price': 5,
              'Rating': 4,
              'location': 'Unit 12, Olde Towne Mall',
              'description': 'Naan and tandoori specialties, from our clay oven.'
            },
            {
              'name': 'Sakura',
              'id': 'sakura',
              'cuisine': 'japanese',
              'opens': '17:00:00',
              'closes': '22:30:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa,Su',
              'price': 3,
              'Rating': 2,
              'location': 'Unit 18, Olde Towne Mall',
              'description': 'Sushi specials daily. We serve fast, friendly, fresh Japanese cuisine.'
            },
            {
              'name': 'Shandong Lu',
              'id': 'shandong',
              'cuisine': 'chinese',
              'opens': '17:00:00',
              'closes': '22:30:00',
              'daysOpen': 'Tu,We,Th,Fr,Sa,Su',
              'price': 4,
              'Rating': 3,
              'location': '335 University',
              'description': 'Szechuan and Mandarin specialities with a fine dining ambiance. Our hot and sour soup is the best in town.'
            },
            {
              'name': 'Curry Galore',
              'id': 'currygalore',
              'cuisine': 'indian',
              'opens': '11:00:00',
              'closes': '22:30:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa',
              'price': 3,
              'Rating': 2,
              'location': '56 Park Ave',
              'description': 'Famous North Indian home cooking. Spicy or mild, as you like it. Delivery available.'
            },
            {
              'name': 'North by Northwest',
              'id': 'north',
              'cuisine': 'cafe',
              'opens': '6:00:00',
              'closes': '18:00:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa,Su',
              'price': 1,
              'Rating': 4,
              'location': '201 University',
              'description': 'Great coffee and snacks. Free wifi.'
            },
            {
              'name': 'Full of Beans',
              'id': 'beans',
              'cuisine': 'cafe',
              'opens': '6:30:00',
              'closes': '20:30:00',
              'daysOpen': 'Mo,We,Fr,Sa,Su',
              'price': 3,
              'Rating': 5,
              'location': '498 College Ave.',
              'description': 'We roast on premises to give you the best cup of coffee in town.'
            },
            {
              'name': 'Tropical Jeeve\'s Cafe',
              'id': 'jeeves',
              'cuisine': 'cafe',
              'opens': '7:00:00',
              'closes': '14:30:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa,Su',
              'price': 2,
              'Rating': 4,
              'location': '550 Milliways Ave',
              'description': 'Hawaiian style coffee, fresh juices, and tropical fruit smoothies.'
            },
            {
              'name': 'Zardoz Cafe',
              'id': 'zardoz',
              'cuisine': 'cafe',
              'opens': '10:30:00',
              'closes': '0:00:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr',
              'price': 4,
              'Rating': 2,
              'location': '6202 Alameda',
              'description': 'Coffee bar and sci-fi bookshop. Come in for an espresso or a slice of our famous pie.'
            },
            {
              'name': 'Angular Pizza',
              'id': 'angular',
              'cuisine': 'pizza',
              'opens': '6:00:00',
              'closes': '0:00:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa,Su',
              'price': 1,
              'Rating': 5,
              'location': '2232 King St.',
              'description': 'Home of the superheroic pizza!'
            },
            {
              'name': 'Flavia',
              'id': 'flavia',
              'cuisine': 'pizza',
              'opens': '11:30:00',
              'closes': '22:00:00',
              'daysOpen': 'Tu,We,Th,Fr,Sa,Su',
              'price': 4,
              'Rating': 5,
              'location': '401 Riddick St.',
              'description': 'Roman-style pizza -- square, the way the gods intended.'
            },
            {
              'name': 'Luigi\'s House of Pies',
              'id': 'luigis',
              'cuisine': 'pizza',
              'opens': '16:30:00',
              'closes': '23:00:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa',
              'price': 2,
              'Rating': 1,
              'location': '5 Garcia Ave.',
              'description': 'Our secret pizza sauce makes our pizza better. We specialize in large groups.'
            },
            {
              'name': 'Thick and Thin',
              'id': 'thick',
              'cuisine': 'pizza',
              'opens': '17:00:00',
              'closes': '23:30:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa,Su',
              'price': 5,
              'Rating': 4,
              'location': '832 Dominican Ave.',
              'description': 'Whether you\'re craving Chicago-style deep dish or thin as a wafer crust, we have you covered in toppings you\'ll love.'
            },
            {
              'name': 'When in Rome',
              'id': 'wheninrome',
              'cuisine': 'pizza',
              'opens': '11:00:00',
              'closes': '21:30:00',
              'daysOpen': 'Mo,We,Fr,Sa,Su',
              'price': 3,
              'Rating': 2,
              'location': '234 Valencia St.',
              'description': 'Authentic Italian pizza in a friendly neighborhood joint.'
            },
            {
              'name': 'Pizza 76',
              'id': 'pizza76',
              'cuisine': 'pizza',
              'opens': '10:30:00',
              'closes': '22:00:00',
              'daysOpen': 'Mo,Tu,We,Th,Fr,Sa,Su',
              'price': 4,
              'Rating': 3,
              'location': '76 Market St.',
              'description': 'Wood-fired pizza with daily ingredients fresh from our farmer\'s market. We make our own mozzarella in house.'
            }
          ];
          return { restaurants };
    }
}

